project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd


format:
  html:
    embed-resources: true
    page-footer: "Copyright 2021, Norah Jones" 
    navbar:
      search: true
      brand-logo: true
  # docx:
  #   reference-doc: reference.docx
  jats: default


  # (other formats)
  # pdf: default



  #   logo: assets/otessa-logo.jpg
  #   pdf-standard: [a-4f, ua-2]
  #   documentclass: scrartcl
  #   papersize: letter
  #   


  typst:
    toc: false
    template-partials:
    - typst-show.typ
    - typst-template.typ
    logo:
      width: 1in
      location: right-top
      padding-right: 0.5in
      padding-top: 0.25in
    # pdf-standard: ua-1
    columns: 1
    font-paths: ["assets/fonts"]
    font: "Roboto"

execute:
  freeze: true

format-links: false



